name: Build and publish AUR on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt-get install -y \
            libpango1.0-dev \
            libcairo2-dev \
            libatk1.0-dev \
            libgtk-4-dev \
            libsoup2.4-dev

      - name: Set up dependencies
        run: |
          export SYSTEM_DEPS_PANGO_NO_PKG_CONFIG="true"
          export SYSTEM_DEPS_PANGO_LIB="pango-1.0"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo‑aur
        run: cargo install cargo-aur

      - name: Generate PKGBUILD & .SRCINFO
        run: |
          cargo aur
          cd target/cargo-aur
          makepkg --printsrcinfo > .SRCINFO

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: hyprviz-bin
          pkgbuild: target/cargo-aur/PKGBUILD
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          commit_message: "Update to ${{ github.ref_name }}‑1"
          updpkgsums: true
          test: false
          ssh_keyscan_types: rsa,ecdsa,ed25519
